module.exports = {
  apps: [
    {
      name: 'forge-ai-studio',
      script: 'npm',
      args: 'run preview -- --port 4173 --host',
      cwd: '/home/nikan/.openclaw/workspace/Forge-AI-Studio',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production'
      },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: 5000,
      max_memory_restart: '500M',
      restart_delay: 1000,
      exp_backoff_restart_delay: 100,
      kill_timeout: 5000,
      listen_timeout: 3000,
      output: '/home/nikan/.openclaw/workspace/Forge-AI-Studio/logs/forge-ai-studio-out.log',
      error: '/home/nikan/.openclaw/workspace/Forge-AI-Studio/logs/forge-ai-studio-err.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'forge-ai-poller',
      script: 'node',
      args: 'poll-openclaw.cjs',
      cwd: '/home/nikan/.openclaw/workspace/Forge-AI-Studio',
      interpreter: 'none',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: 5000,
      restart_delay: 1000,
      exp_backoff_restart_delay: 100,
      output: '/home/nikan/.openclaw/workspace/Forge-AI-Studio/logs/poll-out.log',
      error: '/home/nikan/.openclaw/workspace/Forge-AI-Studio/logs/poll-err.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'forge-ai-tunnel',
      script: '/usr/bin/cloudflared',
      args: 'tunnel run --url localhost:4173 ba1671ff-cbeb-4fe9-83cd-876ac16ede42',
      cwd: '/home/nikan/.openclaw/workspace/Forge-AI-Studio',
      interpreter: 'none',
      watch: false,
      autorestart: true,
      max_restarts: 15,
      min_uptime: 10000,
      restart_delay: 2000,
      exp_backoff_restart_delay: 100,
      output: '/home/nikan/.openclaw/workspace/Forge-AI-Studio/logs/cloudflared-out.log',
      error: '/home/nikan/.openclaw/workspace/Forge-AI-Studio/logs/cloudflared-err.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    }
  ]
};
